control:
  hosts:
    control.tymchenko.lan:
      ansible_host: 192.168.1.103


workers:
  hosts:
    worker1.tymchenko.lan:
      ansible_host: 192.168.1.116
    worker2.tymchenko.lan:
      ansible_host: 192.168.1.111 


all_cluster:
  children:
    control:
    workers:
